Updates gemaakt op de app.
scoreService
Aangepaste details:
fetchLocalScoreData => Structuur aangepast zodat het opslaan gebeurt naar de scorelist op te vullen.
Aangepaste fouten/bugs:
E/Capacitor/Console: File: http://localhost/main.1f05f3d3e67f39e9.js - Line 1 - Msg: ERROR Error: Uncaught (in promise): TypeError: Cannot read properties of null (reading 'push')
    TypeError: Cannot read properties of null (reading 'push') => scoreList is null?
Hoe opgelost? => Ervoor gezorgd dat bij de fetchLocalScoreData gechecked wordt op undefined OF null. Anders wordt er een null waarde terug gegeven i.p.v een lege array waardoor de score natuurlijk niet kan worden toegevoegd.

Rps-arena.html:
Namen en score data worden gebruikt van de opgeslagen huidige score zodat er bij het herhalen geen undefined tevoorschijn komt.
Probleem: Toont altijd vorige lokale score data. Oplossing? => Maak score aan voor dat je op de pagina komt.

Choose name
Typescript kant:
Score wordt hier aangemaakt i.p.v bij de rps arena
goToRpsArena is nu async zodat de score eerst kan worden aangemaakt en ingesteld worden als de huidige score waarvoor gespeeld wordt voordat de speler daar terecht komt.
Verder heeft de functie ook een methode om de score dat getoond moet worden te tonen.

rpsData service:
HTML:
Ids en benaming verandert zodat de nederlandse benaming getoond kan worden als keuze van een speler.
Typescript:
Nederlandse benamingen in switch gebruikt + teruggestuurd wier er gewonnen heeft.
Audio.service
Typescript
Audio gepreload bij setAudioSettingsNative zodat ze audio effectief kan worden afgespeeld.
Loop toegevoegd bij startscreen
Soundeffect
Settings
Typescript
Native check toegevoegd bij het veranderen van de audio om ervoor te zorgen dat de native audio niet aangesproken wordt als men niet op non-native toestel zit.
Startscreen
Typescript:
This.audioService.getCurrentStoredAudioVolume(); toegevoegd om de audio op te halen voor de native app
Effectief de track laten afspelen vanaf het startscreen omdat je anders geen muziek hoort.
Onnodige HideTabbar function weggedaan omdat dit niet nodig is. Het was slechts een test voor andere componenten.